### ISSUE TITLE
Documentation Example for Persisting Units

### ISSUE THREAD

**Issue by blairanderson** [Shopify/measured#117]
Fantastic library that you have created. 

I am curious about the best-practices for validating and persisting these into databases. 

Do you write new validators each time you support weight measurements?

**Comment by kmcphillips** [comment]
Hi! Thanks for the compliment and feedback!

The [measured-rails](https://github.com/Shopify/measured-rails) adapter has a whole section in the [readme](https://github.com/Shopify/measured-rails#validations) about validations. Does that not cover what you need it to do?

**Comment by kmcphillips** [comment]
I guess that makes the assumption that you're using an ActiveRecord backed app. Which is not necessarily true.

**Comment by blairanderson** [comment]
WOW - i missed that 3rd little line of the readme. please ignore me.

**Comment by kmcphillips** [comment]
No problem. Let us know if it doesn’t meet your needs. Hard to know what other projects look like.

**Comment by kmcphillips** [comment]
I will also make it bigger than one line maybe...

**Comment by blairanderson** [comment]
I think adding it to the code sample block for the Gem installation would satisfy all the needs 

Blair
