### ISSUE TITLE
Defect: Unexpected behaviour when building with conflicting conversions 

### ISSUE THREAD

**Issue by arturopie** [Shopify/measured#136]
I'm creating this issue to check if the maintainers also consider this behaviour a defect. If they do, I can work on a PR to fix it.

### Steps to Reproduce

```ruby
System = Measured.build do
  unit "cases", value: "1 pallets"
  unit "pallets", value: "99 cases"
end
```

### Expected Behaviour

Raise exception from `Measured.build`, as we are providing conflicting conversions.

### Actual Behaviour

No exception, and:

```ruby
System.new(1, "cases").convert_to("pallets").to_s
 => "1 pallets"
System.new(1, "pallets").convert_to("cases").to_s
 => "1 cases"
```

## Example 2

```ruby
System = Measured.build do
  unit "pallets", value: "1 liters"
  unit "liters", value: "0.1 cases"
  unit "cases", value: "0.1 pallets"
end

```

### Expected Behaviour

Raise exception from `Measured.build`, as we are providing conflicting conversions.

### Actual Behaviour

No exception, and:

```ruby
System.new(1, "liters")
  .convert_to("cases")
  .convert_to("pallets")
  .convert_to("liters")
  .to_s
 => "0.01 liters"
```

**Comment by kmcphillips** [comment]
Thank you for providing examples!

*Example 1* I believe you are correct this should raise when building the unit system. That behaviour right now is undefined. Presumably there's a check to be added into `UnitSystem` or `UnitSystemBuilder` to check for invalid state.

*Example 2* is the same but just a longer cycle. Seems harder but not impossible.

I think this is just checking that the graph is acyclic?

**Comment by arturopie** [comment]
> I think this is just checking that the graph is acyclic?

I think (from just reading the code), that we could either: 

1. Add a check at the end of `ConversionTableBuilder#generate_table` that makes sure table[unitX][unitY] == table[unitY][unitX] for all unitX and unitY in units
2. or check `from_table[to_unit] == nil || from_table[to_unit]  == 1 / conversion` before doing `from_table[to_unit] = 1 / conversion` and also check for `table[to_unit]` before doing `table[to_unit] = to_table`

I'm leaning more towards option 1, as it's easier to understand.

**Comment by kmcphillips** [comment]
I think I agree with you.

It's non-trivially expensive on each load. But that's why there's the cache.

I wonder what other invalid states can be represented? This gem is designed to be extensible, but really isn't meant for that to be its primary use case. Most people just want distance/weight. So there are very few guard rails and checks for building unit systems.

**Comment by kmcphillips** [comment]
```ruby
  def generate_table
    units.map(&:name).each_with_object({}) do |to_unit, table|
      to_table = {to_unit => Rational(1, 1)}

      table.each do |from_unit, from_table|
        conversion = find_conversion(to: from_unit, from: to_unit)
        to_table[from_unit] = conversion
        from_table[to_unit] = 1 / conversion
      end

      table[to_unit] = to_table
    end
  end
```
This could become something like:

```ruby
  def generate_table
    result = units.map(&:name).each_with_object({}) do |to_unit, table|
      to_table = {to_unit => Rational(1, 1)}

      table.each do |from_unit, from_table|
        conversion = find_conversion(to: from_unit, from: to_unit)
        to_table[from_unit] = conversion
        from_table[to_unit] = 1 / conversion
      end

      table[to_unit] = to_table
    end
    validate_table
    result
  end

  def validate_table
    # perform whatever checks here, and raise a sublcass of `UnitError` when invalid
  end
```
