### ISSUE TITLE
Add an alias to an existing unit

### ISSUE THREAD

**Issue by kushagra-03** [Shopify/measured#146]
Is there a way to add an extra alias to an existing unit? I wanted to add `gm` alias to `Measured::Weight` as an alias for grams. But don't see a straightforward way of accomplishing that. 

Looks like I might have to skip all the units and then redefine them using `Measured.build`, which seems like quite some work to add an alias.

https://github.com/Shopify/measured/issues/146#tasklist-block-e4b8f6e7-6aa0-4dc9-abc7-f1f1ce63264d

**Comment by kushagra-03** [comment]
Thanks for the response, I think Option 2 makes more sense.
Quick question though, do you think it makes sense to introduce this change?

`si_unit :g, aliases: [:gram, :grams, :gm, :gms]`

Just noticed the plural form as well.

I'll go ahead and open up a PR.

**Comment by kmcphillips** [comment]
Fixed in #147
