### ISSUE TITLE
Better serialization and deserialization

### ISSUE THREAD

**Issue by dvisockas** [Shopify/measured#148]
👋 Hi!

If we initialize a weight value and serialize it:
```ruby
weight = Measured::Weight.new(0, :g)
serialized_weight = { value: weight.value, unit: weight.unit.name }.to_json
#=> '{"value":"0\/1","unit":"g"}'
```
If we then deserialize it:
```ruby
deserialized_weight = JSON.parse(serialized_weight)
weight = Measured::Weight.new(deserialized_weight['value'], deserialized_weight['unit'])
#=> ArgumentError: invalid value for BigDecimal(): "0/1"
```

This is the case because `Measured` assumes that [if the first argument is a string - it is parsed as a `BigDecimal`](https://github.com/Shopify/measured/blob/main/lib/measured/measurable.rb#L20).
Maybe it could be a bit smarter and try to parse the value as `Rational` if some condition (maybe just a simple `\d+\\\d+` regex matched)?

**Comment by kmcphillips** [comment]
Hello! Yes this all makes sense. Thank you for the code sample clearly explaining the issue.

I think you identified the correct fix, or at least the first fix that I would try. Would you be willing to submit a PR? I can help you on it if you're stuck and would be happy to review and merge it (though I am on leave though and may not respond super fast).

I would approach it something like...:
* As you identified [here](https://github.com/Shopify/measured/blob/main/lib/measured/measurable.rb#L20) add a `when String` case.
* In that case, do a bit of regex matching on what we think the numeric is in there. Likely it's just as you identified, if it includes a `\` then it's a `Rational`, else `BigDecimal`.
* Add a bunch of test cases to cover this. I don't think this is well tested.

WDYT?

**Comment by dvisockas** [comment]
I'd be happy to submit a PR. Will ping you if I get stuck!
