### ISSUE TITLE
Use Numeric for Measurable

### ISSUE THREAD

**Issue by thegedge** [Shopify/measured#31]
[`Numeric`](https://ruby-doc.org/core-2.3.3/Numeric.html) supplies an interface for classes that act like numbers, and a `Measurable` fits this model. Coercion of `[a, b]` would require converting `b` to the same units of `a`.

This will also allow us to drop the `Comparable` portion of `Measurable` since `Numeric` gives us that for free.

**Comment by kmcphillips** [comment]
👍
