### ISSUE TITLE
Simplify case sensitivity code

### ISSUE THREAD

**Issue by thegedge** [Shopify/measured#32]
Use something other than `case_sensitive` as state for `Conversion`. Some ideas include:

1. Use dependency injection to supply a collection object that will store names/aliases. If case insensitivity is required, this collection should be able to hide that detail.
2. Have a "name mapping" function in `Conversion` that can be overridden by another class (e.g., `CaseSensitiveConversion` would be the identity function and `CaseInsensitiveConversion` would be `#downcase`)

**Comment by kmcphillips** [comment]
I'm ok with this. Case sensitivity was added after and could probably be better thought out.

**Comment by thegedge** [comment]
Completed over several PRs (mostly https://github.com/Shopify/measured/pull/53 and https://github.com/Shopify/measured/pull/29)
