### ISSUE TITLE
Convert `ConversionTable` to module functions

### ISSUE THREAD

**Issue by thegedge** [Shopify/measured#38]
`ConversionTable` makes no sense, but rather encapsulates a set of operations to create a `Hash` for unit conversion. Since it's not meant to stick around we should just stick to exposing a function.

**Comment by kmcphillips** [comment]
I'm pretty so so on this. It's just a small object to encapsulate a set of resolution operations, generating an output. 

If you mean switching it from instantiation to module functions I'm ok with that.

**Comment by thegedge** [comment]
> If you mean switching it from instantiation to module functions I'm ok with that.

Yep, that's what I mean. If there's no need for polymorphism, procedural programming is a perfectly good paradigm 😄 

I'll be sure to double check and make sure this won't cause any issues when it comes to testability, but I don't think it will.

**Comment by kmcphillips** [comment]
No that should be good then. 👌
