### ISSUE TITLE
Make Conversion immutable

### ISSUE THREAD

**Issue by thegedge** [Shopify/measured#47]
I see little to no value in having the ability to add units to `Measured::Conversion` after it's been created. Immutability again will give us some nice benefits here, in particular with how I'd approach https://github.com/Shopify/measured/issues/32 (increased performance).

I think a DSL or configuration step would be really nice here, which is basically how we use it today. I'll throw out a couple of options:

## Close to what we have today
```ruby
class Measured::Length < Measured::Measurable
  conversion.configure do
    case_sensitive true

    base :m, aliases: [:meter, :metre, :meters, :metres]

    unit :cm, value: "0.01 m", aliases: [:centimeter, :centimetre, :centimeters, :centimetres],
  end
end
```

## DSL
```ruby
Measured::Length = Measured::Measurable.build("Length") do
  case_sensitive false

  base :m, aliases: [:meter, :metre, :meters, :metres]

  unit :cm, value: "0.01   m", aliases: [:centimeter, :centimetre, :centimeters, :centimetres]
  unit :mm, value: "0.001  m", aliases: [:millimeter, :millimetre, :millimeters, :millimetres]
  unit :in, value: "0.0254 m", aliases: [:inch, :inches]
  unit :ft, value: "0.3048 m", aliases: [:foot, :feet]
  unit :yd, value: "0.9144 m", aliases: [:yard, :yards]
end
```

**Comment by kmcphillips** [comment]
I'm pretty sure the `("Length")` is unnecessary. 

Also, the `build` shouldn't be on the `Measured::Measurable` object because then it's pulled around through every base class instance (`Weight`, `Length`, etc). 

Maybe more:

```ruby
Measured::Length = Measured.build do
  base :m, aliases: [:meter, :metre, :meters, :metres]

  unit :cm, value: "0.01   m", aliases: [:centimeter, :centimetre, :centimeters, :centimetres]
  unit :mm, value: "0.001  m", aliases: [:millimeter, :millimetre, :millimeters, :millimetres]
  unit :in, value: "0.0254 m", aliases: [:inch, :inches]
```

**Comment by kmcphillips** [comment]
Also need to make sure that the call to `build` creates a subclass of `Measurable`, and that trying to subclass it without use of the DSL will fail too.

**Comment by kmcphillips** [comment]
Either that or remove the superclass entirely and make it a mixin.
