### ISSUE TITLE
Remove base unit

### ISSUE THREAD

**Issue by kmcphillips** [Shopify/measured#60]
We define `base` unit without a value, then a `unit value: 'other unit'`.

Explore if we can remove the `base` altogether. Building the parse graph may be more complex, but we can experiment with just processing them in order and not depending on a base.

This may help us with #59 that don't share a common zero point, and simply express units relative to other units.

**Comment by thegedge** [comment]
It's definitely unused. I love 🔥 ing code.

**Comment by kmcphillips** [comment]
It may be as simple as rather than saying:

```ruby
base :g
unit :kg, value: "1000 g"
```

We can just give everything a value:
```ruby
unit :g, value: "0.001 kg"
unit :kg, value: "1000 g"
```

**Comment by kmcphillips** [comment]
Or maybe even just `1`
