### ISSUE TITLE
Make adding units with SI prefixes simpler

### ISSUE THREAD

**Issue by thegedge** [Shopify/measured#88]
I'm thinking we could add an SI helper when building a unit system, which will generate units with the SI prefixes added. Something along the lines:

```ruby
si_unit :g, aliases: [:gram, :grams]
unit :g, aliases: [:gram, :grams], with_si_prefixes: true
```

This would generate kilograms, megagrams, micrograms, etc.

**Comment by kirinrastogi** [comment]
What range would this go to? 10<sup>9</sup> to 10<sup>-9</sup> or even more?

**Comment by kirinrastogi** [comment]
I have started on this, and I don't know if the approach I am taking is good.

I was going to create a class ```Measured::SIUnitSystemBuilder```
with ```def si_unit(unit_name, aliases: [], value: nil, range = 9)```
The class would have two arrays, each with every 3 prefixes, and they can be as long as needed
```[:k, :M, :G]```, and ```[:m, :μ, :n]``` would be snippets of them

Then something would iterate over these and call ```build_unit``` them, with default aliases ```"#{unit_name}s"```

Am I on the right track here?

**Comment by thegedge** [comment]
From browsing around the web it looks like there are 20 prefixes (see [Wikipedia](https://en.wikipedia.org/wiki/Metric_prefix#List_of_SI_prefixes), for example), so I'd go with those.

I'll address your other questions in your (wip) PR!
